language: go

go:
  - 1.6

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update

script:
  - ./enforce_gofmt.sh
  - ./test.sh
  - gometalinter --deadline=15s ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
